// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf7NHd7JidYB7dg-CMQT_z7rj-AYoJ11o',
    appId: '1:386478297945:web:a944ddbde756ebf956b248',
    messagingSenderId: '386478297945',
    projectId: 'nurseflutter-20145',
    authDomain: 'nurseflutter-20145.firebaseapp.com',
    storageBucket: 'nurseflutter-20145.appspot.com',
    measurementId: 'G-M9LFBWCBKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxXTRlK3DHM0K3CC80b_PdjCcZT73sN7I',
    appId: '1:386478297945:android:0dd2932bd5af79a856b248',
    messagingSenderId: '386478297945',
    projectId: 'nurseflutter-20145',
    storageBucket: 'nurseflutter-20145.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCjtGCR1h9akzVX33160OAd7B0bGXGiBY',
    appId: '1:386478297945:ios:ef4853a1ddae571256b248',
    messagingSenderId: '386478297945',
    projectId: 'nurseflutter-20145',
    storageBucket: 'nurseflutter-20145.appspot.com',
    iosClientId: '386478297945-kp34oi1cm83f92b0por6uk4m3gucqksf.apps.googleusercontent.com',
    iosBundleId: 'com.example.primeiro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCjtGCR1h9akzVX33160OAd7B0bGXGiBY',
    appId: '1:386478297945:ios:ef4853a1ddae571256b248',
    messagingSenderId: '386478297945',
    projectId: 'nurseflutter-20145',
    storageBucket: 'nurseflutter-20145.appspot.com',
    iosClientId: '386478297945-kp34oi1cm83f92b0por6uk4m3gucqksf.apps.googleusercontent.com',
    iosBundleId: 'com.example.primeiro',
  );
}
